# Generated by Django 5.0.7 on 2024-09-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', "Men's"), ('women', "Women's"), ('baby', "Baby's")], max_length=255),
        ),
    ]
