# Generated by Django 5.0.7 on 2024-09-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
